REPORT ZPCIM001.

TABLES: IMTP.

DATA: T_BPCU LIKE BPCU OCCURS 0 WITH HEADER LINE.
PARAMETERS: PROGRAM LIKE IMTP-PRNAM,
            FYEAR LIKE IMTP-GJAHR.

SELECT SINGLE * FROM IMTP
                WHERE PRNAM = PROGRAM
                 AND  GJAHR = FYEAR.
CHECK SY-SUBRC = 0.

CALL FUNCTION 'KBPS_FIND_LEDGER'
     EXPORTING
         CURRENCY   = IMTP-WAERS
         NEW_LEDGER = 'X'
         PERIV      = IMTP-PERIV
*     IMPORTING
*          LEDGER     =
*          OP_DECIM   =
     TABLES
          BP_CUR     = T_BPCU
     EXCEPTIONS
          NO_LEDGER  = 1
          OTHERS     = 2.
