*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 03.02.2003 at 08:53:29 by user ASCHERBI
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZPSDEVTOP.                        " Global Data
  INCLUDE LZPSDEVUXX.                        " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZPSDEVF00                              . " subprograms
  INCLUDE LZPSDEVI00                              . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZPSDEVF...                        " Subprograms
* INCLUDE LZPSDEVO...                        " PBO-Modules
* INCLUDE LZPSDEVI...                        " PAI-Modules
